
services:
  database:
    image: postgres:17
    ports:
      - "5455:5432"
    environment:
      POSTGRES_USER: cloudsqliamuser
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bidrag-automatisk-jobb

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    expose:
      - '29092'
    environment:
      # --- KRaft konfigurasjon (Kombinert Broker og Controller) ---
      KAFKA_NODE_ID: 1
      # Generert med: kafka-storage.sh random-uuid
      CLUSTER_ID: 'Y74ALMaiRPSnXo4cD0HjFQ'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'

      # --- Listener Configuration ---
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092,CONTROLLER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'